// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: value-objects/availability-dto.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Ladesa.TimetableGenerator.Service.Infrastructure.Protos {
  #region Enums

  #endregion

  #region Messages
  public sealed partial class AvailabilityDto : pb::IMessage<AvailabilityDto>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AvailabilityDto> _parser = new pb::MessageParser<AvailabilityDto>(() => new AvailabilityDto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<AvailabilityDto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.AvailabilityDtoReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AvailabilityDto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AvailabilityDto(AvailabilityDto other) : this() {
      type_ = other.type_;
      switch (other.RegraCase) {
        case RegraOneofCase.Compount:
          Compount = other.Compount.Clone();
          break;
        case RegraOneofCase.UnavailableWeekDay:
          UnavailableWeekDay = other.UnavailableWeekDay.Clone();
          break;
        case RegraOneofCase.UnavailableWeekDays:
          UnavailableWeekDays = other.UnavailableWeekDays.Clone();
          break;
        case RegraOneofCase.UnavailableTimeSlot:
          UnavailableTimeSlot = other.UnavailableTimeSlot.Clone();
          break;
        case RegraOneofCase.UnavailableSpecificDate:
          UnavailableSpecificDate = other.UnavailableSpecificDate.Clone();
          break;
        case RegraOneofCase.UnavailableDateRange:
          UnavailableDateRange = other.UnavailableDateRange.Clone();
          break;
        case RegraOneofCase.UnavailableMonthDay:
          UnavailableMonthDay = other.UnavailableMonthDay.Clone();
          break;
        case RegraOneofCase.UnavailableYearMonths:
          UnavailableYearMonths = other.UnavailableYearMonths.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AvailabilityDto Clone() {
      return new AvailabilityDto(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.AvailabilityTypeDto type_ = global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.AvailabilityTypeDto.Compound;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.AvailabilityTypeDto Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "compount" field.</summary>
    public const int CompountFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.AvailabilityCompoundDto Compount {
      get { return regraCase_ == RegraOneofCase.Compount ? (global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.AvailabilityCompoundDto) regra_ : null; }
      set {
        regra_ = value;
        regraCase_ = value == null ? RegraOneofCase.None : RegraOneofCase.Compount;
      }
    }

    /// <summary>Field number for the "unavailable_week_day" field.</summary>
    public const int UnavailableWeekDayFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.AvailabilityUnavailableWeekDayDto UnavailableWeekDay {
      get { return regraCase_ == RegraOneofCase.UnavailableWeekDay ? (global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.AvailabilityUnavailableWeekDayDto) regra_ : null; }
      set {
        regra_ = value;
        regraCase_ = value == null ? RegraOneofCase.None : RegraOneofCase.UnavailableWeekDay;
      }
    }

    /// <summary>Field number for the "unavailable_week_days" field.</summary>
    public const int UnavailableWeekDaysFieldNumber = 4;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.AvailabilityUnavailableWeekDaysDto UnavailableWeekDays {
      get { return regraCase_ == RegraOneofCase.UnavailableWeekDays ? (global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.AvailabilityUnavailableWeekDaysDto) regra_ : null; }
      set {
        regra_ = value;
        regraCase_ = value == null ? RegraOneofCase.None : RegraOneofCase.UnavailableWeekDays;
      }
    }

    /// <summary>Field number for the "unavailable_time_slot" field.</summary>
    public const int UnavailableTimeSlotFieldNumber = 5;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.AvailabilityUnavailableTimeSlotDto UnavailableTimeSlot {
      get { return regraCase_ == RegraOneofCase.UnavailableTimeSlot ? (global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.AvailabilityUnavailableTimeSlotDto) regra_ : null; }
      set {
        regra_ = value;
        regraCase_ = value == null ? RegraOneofCase.None : RegraOneofCase.UnavailableTimeSlot;
      }
    }

    /// <summary>Field number for the "unavailable_specific_date" field.</summary>
    public const int UnavailableSpecificDateFieldNumber = 6;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.AvailabilityUnavailableSpecificDateDto UnavailableSpecificDate {
      get { return regraCase_ == RegraOneofCase.UnavailableSpecificDate ? (global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.AvailabilityUnavailableSpecificDateDto) regra_ : null; }
      set {
        regra_ = value;
        regraCase_ = value == null ? RegraOneofCase.None : RegraOneofCase.UnavailableSpecificDate;
      }
    }

    /// <summary>Field number for the "unavailable_date_range" field.</summary>
    public const int UnavailableDateRangeFieldNumber = 7;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.AvailabilityUnavailableDateRangeDto UnavailableDateRange {
      get { return regraCase_ == RegraOneofCase.UnavailableDateRange ? (global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.AvailabilityUnavailableDateRangeDto) regra_ : null; }
      set {
        regra_ = value;
        regraCase_ = value == null ? RegraOneofCase.None : RegraOneofCase.UnavailableDateRange;
      }
    }

    /// <summary>Field number for the "unavailable_month_day" field.</summary>
    public const int UnavailableMonthDayFieldNumber = 8;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.AvailabilityUnavailableMonthDayDto UnavailableMonthDay {
      get { return regraCase_ == RegraOneofCase.UnavailableMonthDay ? (global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.AvailabilityUnavailableMonthDayDto) regra_ : null; }
      set {
        regra_ = value;
        regraCase_ = value == null ? RegraOneofCase.None : RegraOneofCase.UnavailableMonthDay;
      }
    }

    /// <summary>Field number for the "unavailable_year_months" field.</summary>
    public const int UnavailableYearMonthsFieldNumber = 9;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.AvailabilityUnavailableYearMonthsDto UnavailableYearMonths {
      get { return regraCase_ == RegraOneofCase.UnavailableYearMonths ? (global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.AvailabilityUnavailableYearMonthsDto) regra_ : null; }
      set {
        regra_ = value;
        regraCase_ = value == null ? RegraOneofCase.None : RegraOneofCase.UnavailableYearMonths;
      }
    }

    private object regra_;
    /// <summary>Enum of possible cases for the "regra" oneof.</summary>
    public enum RegraOneofCase {
      None = 0,
      Compount = 2,
      UnavailableWeekDay = 3,
      UnavailableWeekDays = 4,
      UnavailableTimeSlot = 5,
      UnavailableSpecificDate = 6,
      UnavailableDateRange = 7,
      UnavailableMonthDay = 8,
      UnavailableYearMonths = 9,
    }
    private RegraOneofCase regraCase_ = RegraOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RegraOneofCase RegraCase {
      get { return regraCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearRegra() {
      regraCase_ = RegraOneofCase.None;
      regra_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as AvailabilityDto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(AvailabilityDto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if (!object.Equals(Compount, other.Compount)) return false;
      if (!object.Equals(UnavailableWeekDay, other.UnavailableWeekDay)) return false;
      if (!object.Equals(UnavailableWeekDays, other.UnavailableWeekDays)) return false;
      if (!object.Equals(UnavailableTimeSlot, other.UnavailableTimeSlot)) return false;
      if (!object.Equals(UnavailableSpecificDate, other.UnavailableSpecificDate)) return false;
      if (!object.Equals(UnavailableDateRange, other.UnavailableDateRange)) return false;
      if (!object.Equals(UnavailableMonthDay, other.UnavailableMonthDay)) return false;
      if (!object.Equals(UnavailableYearMonths, other.UnavailableYearMonths)) return false;
      if (RegraCase != other.RegraCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Type != global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.AvailabilityTypeDto.Compound) hash ^= Type.GetHashCode();
      if (regraCase_ == RegraOneofCase.Compount) hash ^= Compount.GetHashCode();
      if (regraCase_ == RegraOneofCase.UnavailableWeekDay) hash ^= UnavailableWeekDay.GetHashCode();
      if (regraCase_ == RegraOneofCase.UnavailableWeekDays) hash ^= UnavailableWeekDays.GetHashCode();
      if (regraCase_ == RegraOneofCase.UnavailableTimeSlot) hash ^= UnavailableTimeSlot.GetHashCode();
      if (regraCase_ == RegraOneofCase.UnavailableSpecificDate) hash ^= UnavailableSpecificDate.GetHashCode();
      if (regraCase_ == RegraOneofCase.UnavailableDateRange) hash ^= UnavailableDateRange.GetHashCode();
      if (regraCase_ == RegraOneofCase.UnavailableMonthDay) hash ^= UnavailableMonthDay.GetHashCode();
      if (regraCase_ == RegraOneofCase.UnavailableYearMonths) hash ^= UnavailableYearMonths.GetHashCode();
      hash ^= (int) regraCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Type != global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.AvailabilityTypeDto.Compound) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (regraCase_ == RegraOneofCase.Compount) {
        output.WriteRawTag(18);
        output.WriteMessage(Compount);
      }
      if (regraCase_ == RegraOneofCase.UnavailableWeekDay) {
        output.WriteRawTag(26);
        output.WriteMessage(UnavailableWeekDay);
      }
      if (regraCase_ == RegraOneofCase.UnavailableWeekDays) {
        output.WriteRawTag(34);
        output.WriteMessage(UnavailableWeekDays);
      }
      if (regraCase_ == RegraOneofCase.UnavailableTimeSlot) {
        output.WriteRawTag(42);
        output.WriteMessage(UnavailableTimeSlot);
      }
      if (regraCase_ == RegraOneofCase.UnavailableSpecificDate) {
        output.WriteRawTag(50);
        output.WriteMessage(UnavailableSpecificDate);
      }
      if (regraCase_ == RegraOneofCase.UnavailableDateRange) {
        output.WriteRawTag(58);
        output.WriteMessage(UnavailableDateRange);
      }
      if (regraCase_ == RegraOneofCase.UnavailableMonthDay) {
        output.WriteRawTag(66);
        output.WriteMessage(UnavailableMonthDay);
      }
      if (regraCase_ == RegraOneofCase.UnavailableYearMonths) {
        output.WriteRawTag(74);
        output.WriteMessage(UnavailableYearMonths);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Type != global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.AvailabilityTypeDto.Compound) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (regraCase_ == RegraOneofCase.Compount) {
        output.WriteRawTag(18);
        output.WriteMessage(Compount);
      }
      if (regraCase_ == RegraOneofCase.UnavailableWeekDay) {
        output.WriteRawTag(26);
        output.WriteMessage(UnavailableWeekDay);
      }
      if (regraCase_ == RegraOneofCase.UnavailableWeekDays) {
        output.WriteRawTag(34);
        output.WriteMessage(UnavailableWeekDays);
      }
      if (regraCase_ == RegraOneofCase.UnavailableTimeSlot) {
        output.WriteRawTag(42);
        output.WriteMessage(UnavailableTimeSlot);
      }
      if (regraCase_ == RegraOneofCase.UnavailableSpecificDate) {
        output.WriteRawTag(50);
        output.WriteMessage(UnavailableSpecificDate);
      }
      if (regraCase_ == RegraOneofCase.UnavailableDateRange) {
        output.WriteRawTag(58);
        output.WriteMessage(UnavailableDateRange);
      }
      if (regraCase_ == RegraOneofCase.UnavailableMonthDay) {
        output.WriteRawTag(66);
        output.WriteMessage(UnavailableMonthDay);
      }
      if (regraCase_ == RegraOneofCase.UnavailableYearMonths) {
        output.WriteRawTag(74);
        output.WriteMessage(UnavailableYearMonths);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Type != global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.AvailabilityTypeDto.Compound) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (regraCase_ == RegraOneofCase.Compount) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Compount);
      }
      if (regraCase_ == RegraOneofCase.UnavailableWeekDay) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(UnavailableWeekDay);
      }
      if (regraCase_ == RegraOneofCase.UnavailableWeekDays) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(UnavailableWeekDays);
      }
      if (regraCase_ == RegraOneofCase.UnavailableTimeSlot) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(UnavailableTimeSlot);
      }
      if (regraCase_ == RegraOneofCase.UnavailableSpecificDate) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(UnavailableSpecificDate);
      }
      if (regraCase_ == RegraOneofCase.UnavailableDateRange) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(UnavailableDateRange);
      }
      if (regraCase_ == RegraOneofCase.UnavailableMonthDay) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(UnavailableMonthDay);
      }
      if (regraCase_ == RegraOneofCase.UnavailableYearMonths) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(UnavailableYearMonths);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(AvailabilityDto other) {
      if (other == null) {
        return;
      }
      if (other.Type != global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.AvailabilityTypeDto.Compound) {
        Type = other.Type;
      }
      switch (other.RegraCase) {
        case RegraOneofCase.Compount:
          if (Compount == null) {
            Compount = new global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.AvailabilityCompoundDto();
          }
          Compount.MergeFrom(other.Compount);
          break;
        case RegraOneofCase.UnavailableWeekDay:
          if (UnavailableWeekDay == null) {
            UnavailableWeekDay = new global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.AvailabilityUnavailableWeekDayDto();
          }
          UnavailableWeekDay.MergeFrom(other.UnavailableWeekDay);
          break;
        case RegraOneofCase.UnavailableWeekDays:
          if (UnavailableWeekDays == null) {
            UnavailableWeekDays = new global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.AvailabilityUnavailableWeekDaysDto();
          }
          UnavailableWeekDays.MergeFrom(other.UnavailableWeekDays);
          break;
        case RegraOneofCase.UnavailableTimeSlot:
          if (UnavailableTimeSlot == null) {
            UnavailableTimeSlot = new global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.AvailabilityUnavailableTimeSlotDto();
          }
          UnavailableTimeSlot.MergeFrom(other.UnavailableTimeSlot);
          break;
        case RegraOneofCase.UnavailableSpecificDate:
          if (UnavailableSpecificDate == null) {
            UnavailableSpecificDate = new global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.AvailabilityUnavailableSpecificDateDto();
          }
          UnavailableSpecificDate.MergeFrom(other.UnavailableSpecificDate);
          break;
        case RegraOneofCase.UnavailableDateRange:
          if (UnavailableDateRange == null) {
            UnavailableDateRange = new global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.AvailabilityUnavailableDateRangeDto();
          }
          UnavailableDateRange.MergeFrom(other.UnavailableDateRange);
          break;
        case RegraOneofCase.UnavailableMonthDay:
          if (UnavailableMonthDay == null) {
            UnavailableMonthDay = new global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.AvailabilityUnavailableMonthDayDto();
          }
          UnavailableMonthDay.MergeFrom(other.UnavailableMonthDay);
          break;
        case RegraOneofCase.UnavailableYearMonths:
          if (UnavailableYearMonths == null) {
            UnavailableYearMonths = new global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.AvailabilityUnavailableYearMonthsDto();
          }
          UnavailableYearMonths.MergeFrom(other.UnavailableYearMonths);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Type = (global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.AvailabilityTypeDto) input.ReadEnum();
            break;
          }
          case 18: {
            global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.AvailabilityCompoundDto subBuilder = new global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.AvailabilityCompoundDto();
            if (regraCase_ == RegraOneofCase.Compount) {
              subBuilder.MergeFrom(Compount);
            }
            input.ReadMessage(subBuilder);
            Compount = subBuilder;
            break;
          }
          case 26: {
            global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.AvailabilityUnavailableWeekDayDto subBuilder = new global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.AvailabilityUnavailableWeekDayDto();
            if (regraCase_ == RegraOneofCase.UnavailableWeekDay) {
              subBuilder.MergeFrom(UnavailableWeekDay);
            }
            input.ReadMessage(subBuilder);
            UnavailableWeekDay = subBuilder;
            break;
          }
          case 34: {
            global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.AvailabilityUnavailableWeekDaysDto subBuilder = new global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.AvailabilityUnavailableWeekDaysDto();
            if (regraCase_ == RegraOneofCase.UnavailableWeekDays) {
              subBuilder.MergeFrom(UnavailableWeekDays);
            }
            input.ReadMessage(subBuilder);
            UnavailableWeekDays = subBuilder;
            break;
          }
          case 42: {
            global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.AvailabilityUnavailableTimeSlotDto subBuilder = new global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.AvailabilityUnavailableTimeSlotDto();
            if (regraCase_ == RegraOneofCase.UnavailableTimeSlot) {
              subBuilder.MergeFrom(UnavailableTimeSlot);
            }
            input.ReadMessage(subBuilder);
            UnavailableTimeSlot = subBuilder;
            break;
          }
          case 50: {
            global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.AvailabilityUnavailableSpecificDateDto subBuilder = new global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.AvailabilityUnavailableSpecificDateDto();
            if (regraCase_ == RegraOneofCase.UnavailableSpecificDate) {
              subBuilder.MergeFrom(UnavailableSpecificDate);
            }
            input.ReadMessage(subBuilder);
            UnavailableSpecificDate = subBuilder;
            break;
          }
          case 58: {
            global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.AvailabilityUnavailableDateRangeDto subBuilder = new global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.AvailabilityUnavailableDateRangeDto();
            if (regraCase_ == RegraOneofCase.UnavailableDateRange) {
              subBuilder.MergeFrom(UnavailableDateRange);
            }
            input.ReadMessage(subBuilder);
            UnavailableDateRange = subBuilder;
            break;
          }
          case 66: {
            global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.AvailabilityUnavailableMonthDayDto subBuilder = new global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.AvailabilityUnavailableMonthDayDto();
            if (regraCase_ == RegraOneofCase.UnavailableMonthDay) {
              subBuilder.MergeFrom(UnavailableMonthDay);
            }
            input.ReadMessage(subBuilder);
            UnavailableMonthDay = subBuilder;
            break;
          }
          case 74: {
            global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.AvailabilityUnavailableYearMonthsDto subBuilder = new global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.AvailabilityUnavailableYearMonthsDto();
            if (regraCase_ == RegraOneofCase.UnavailableYearMonths) {
              subBuilder.MergeFrom(UnavailableYearMonths);
            }
            input.ReadMessage(subBuilder);
            UnavailableYearMonths = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Type = (global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.AvailabilityTypeDto) input.ReadEnum();
            break;
          }
          case 18: {
            global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.AvailabilityCompoundDto subBuilder = new global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.AvailabilityCompoundDto();
            if (regraCase_ == RegraOneofCase.Compount) {
              subBuilder.MergeFrom(Compount);
            }
            input.ReadMessage(subBuilder);
            Compount = subBuilder;
            break;
          }
          case 26: {
            global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.AvailabilityUnavailableWeekDayDto subBuilder = new global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.AvailabilityUnavailableWeekDayDto();
            if (regraCase_ == RegraOneofCase.UnavailableWeekDay) {
              subBuilder.MergeFrom(UnavailableWeekDay);
            }
            input.ReadMessage(subBuilder);
            UnavailableWeekDay = subBuilder;
            break;
          }
          case 34: {
            global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.AvailabilityUnavailableWeekDaysDto subBuilder = new global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.AvailabilityUnavailableWeekDaysDto();
            if (regraCase_ == RegraOneofCase.UnavailableWeekDays) {
              subBuilder.MergeFrom(UnavailableWeekDays);
            }
            input.ReadMessage(subBuilder);
            UnavailableWeekDays = subBuilder;
            break;
          }
          case 42: {
            global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.AvailabilityUnavailableTimeSlotDto subBuilder = new global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.AvailabilityUnavailableTimeSlotDto();
            if (regraCase_ == RegraOneofCase.UnavailableTimeSlot) {
              subBuilder.MergeFrom(UnavailableTimeSlot);
            }
            input.ReadMessage(subBuilder);
            UnavailableTimeSlot = subBuilder;
            break;
          }
          case 50: {
            global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.AvailabilityUnavailableSpecificDateDto subBuilder = new global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.AvailabilityUnavailableSpecificDateDto();
            if (regraCase_ == RegraOneofCase.UnavailableSpecificDate) {
              subBuilder.MergeFrom(UnavailableSpecificDate);
            }
            input.ReadMessage(subBuilder);
            UnavailableSpecificDate = subBuilder;
            break;
          }
          case 58: {
            global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.AvailabilityUnavailableDateRangeDto subBuilder = new global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.AvailabilityUnavailableDateRangeDto();
            if (regraCase_ == RegraOneofCase.UnavailableDateRange) {
              subBuilder.MergeFrom(UnavailableDateRange);
            }
            input.ReadMessage(subBuilder);
            UnavailableDateRange = subBuilder;
            break;
          }
          case 66: {
            global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.AvailabilityUnavailableMonthDayDto subBuilder = new global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.AvailabilityUnavailableMonthDayDto();
            if (regraCase_ == RegraOneofCase.UnavailableMonthDay) {
              subBuilder.MergeFrom(UnavailableMonthDay);
            }
            input.ReadMessage(subBuilder);
            UnavailableMonthDay = subBuilder;
            break;
          }
          case 74: {
            global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.AvailabilityUnavailableYearMonthsDto subBuilder = new global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.AvailabilityUnavailableYearMonthsDto();
            if (regraCase_ == RegraOneofCase.UnavailableYearMonths) {
              subBuilder.MergeFrom(UnavailableYearMonths);
            }
            input.ReadMessage(subBuilder);
            UnavailableYearMonths = subBuilder;
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
