// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: messages/generator-response.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Ladesa.TimetableGenerator.Service.Infrastructure.Protos {

  /// <summary>Holder for reflection information generated from messages/generator-response.proto</summary>
  public static partial class GeneratorResponseReflection {

    #region Descriptor
    /// <summary>File descriptor for messages/generator-response.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GeneratorResponseReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiFtZXNzYWdlcy9nZW5lcmF0b3ItcmVzcG9uc2UucHJvdG8SHExhZGVzYS5U",
            "aW1ldGFibGVHZW5lcmF0b3IudjEaJmVudGl0aWVzL2dlbmVyYXRlZC10aW1l",
            "dGFibGUtZHRvLnByb3RvIpkBChRHZW5lcmF0b3JSZXNwb25zZUR0bxIPCgdz",
            "dWNjZXNzGAEgASgIEg8KB21lc3NhZ2UYAiABKAkSUQoUZ2VuZXJhdGVkX3Rp",
            "bWV0YWJsZXMYAyADKAsyMy5MYWRlc2EuVGltZXRhYmxlR2VuZXJhdG9yLnYx",
            "LkdlbmVyYXRlZFRpbWV0YWJsZUR0bxIMCgRkYXRlGAQgASgJYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.GeneratedTimetableDtoReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.GeneratorResponseDto), global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.GeneratorResponseDto.Parser, new[]{ "Success", "Message", "GeneratedTimetables", "Date" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages

  #endregion

}

#endregion Designer generated code
