// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: messages/generator-payload.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Ladesa.TimetableGenerator.Service.Infrastructure.Protos {

  /// <summary>Holder for reflection information generated from messages/generator-payload.proto</summary>
  public static partial class GeneratorPayloadReflection {

    #region Descriptor
    /// <summary>File descriptor for messages/generator-payload.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GeneratorPayloadReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiBtZXNzYWdlcy9nZW5lcmF0b3ItcGF5bG9hZC5wcm90bxIcTGFkZXNhLlRp",
            "bWV0YWJsZUdlbmVyYXRvci52MRoYZW50aXRpZXMvZGlhcnktZHRvLnByb3Rv",
            "GhplbnRpdGllcy90ZWFjaGVyLWR0by5wcm90bxoYZW50aXRpZXMvZ3JvdXAt",
            "ZHRvLnByb3RvGiF2YWx1ZS1vYmplY3RzL3RpbWUtc2xvdC1kdG8ucHJvdG8i",
            "ugIKE0dlbmVyYXRvclBheWxvYWREdG8SEgoKcmVxdWVzdF9pZBgBIAEoCRIS",
            "CgpkYXRlX3N0YXJ0GAIgASgJEhAKCGRhdGVfZW5kGAMgASgJEjYKBmRpYXJ5",
            "cxgEIAMoCzImLkxhZGVzYS5UaW1ldGFibGVHZW5lcmF0b3IudjEuRGlhcnlE",
            "dG8SOgoIdGVhY2hlcnMYBSADKAsyKC5MYWRlc2EuVGltZXRhYmxlR2VuZXJh",
            "dG9yLnYxLlRlYWNoZXJEdG8SNgoGZ3JvdXBzGAYgAygLMiYuTGFkZXNhLlRp",
            "bWV0YWJsZUdlbmVyYXRvci52MS5Hcm91cER0bxI9Cgp0aW1lX3Nsb3RzGAcg",
            "AygLMikuTGFkZXNhLlRpbWV0YWJsZUdlbmVyYXRvci52MS5UaW1lU2xvdER0",
            "b2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.DiaryDtoReflection.Descriptor, global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.TeacherDtoReflection.Descriptor, global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.GroupDtoReflection.Descriptor, global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.TimeSlotDtoReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.GeneratorPayloadDto), global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.GeneratorPayloadDto.Parser, new[]{ "RequestId", "DateStart", "DateEnd", "Diarys", "Teachers", "Groups", "TimeSlots" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages

  #endregion

}

#endregion Designer generated code
