// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: value-objects/week-day-dto.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Ladesa.TimetableGenerator.Service.Infrastructure.Protos {
  #region Enums
  public enum WeekDayDto {
    [pbr::OriginalName("Sunday")] Sunday = 0,
    [pbr::OriginalName("Monday")] Monday = 1,
    [pbr::OriginalName("Tuesday")] Tuesday = 2,
    [pbr::OriginalName("Wednesday")] Wednesday = 3,
    [pbr::OriginalName("Thursday")] Thursday = 4,
    [pbr::OriginalName("Friday")] Friday = 5,
    [pbr::OriginalName("Saturday")] Saturday = 6,
  }

  #endregion

}

#endregion Designer generated code
