<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup Label="Dependencies">
    <PackageReference Include="Google.Protobuf" Version="3.33.0"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core\Core.csproj"/>
  </ItemGroup>

</Project>
