version: 2
updates:
  - package-ecosystem: nuget
    directory: "/gerar-horario"
    schedule:
      interval: daily
    open-pull-requests-limit: 3

  - package-ecosystem: github-actions
    directory: "/.github/workflows"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
