x-podman:
  in_pod: false
  pod_args: --replace true

services:
  timetable-generator-service:
    user: root

    build:
      context: .
      dockerfile: Dockerfile
      target: devcontainer

    command: bash -c 'echo "Container Iniciado! Entre com shell rodando podman compose exec timetable-generator-service bash"; sleep infinity;'

    working_dir: /app/Ladesa.TimetableGenerator
    userns_mode: keep-id:uid=1000,gid=1000

    env_file:
      - .env

    volumes:
      - .:/app:z

    ports:
      - 8080:8080

  message-broker:
    image: docker.io/rabbitmq:3.13-management-alpine
    container_name: rabbitmq
    env_file:
      - .env
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    ports:
      - 5672:5672 # Broker
      - 15672:15672 # Management UI

volumes:
  rabbitmq-data:
