x-podman:
  in_pod: false

services:
  timetable-generator-service:
    build:
      context: .
      dockerfile: Dockerfile
      target: devcontainer

    user: root
    userns_mode: keep-id:uid=1000,gid=1000

    command: sleep infinity

    working_dir: /app/Ladesa.TimetableGenerator

    volumes:
      - .:/app:z

  message-broker:
    image: docker.io/bitnami/rabbitmq:3.12
    container_name: sisgea-message-broker
    env_file:
      - .env
    volumes:
      - "sisgea-message-broker-data:/bitnami/rabbitmq/mnesia"
    ports:
      - 5672:5672
      - 15672:15672

volumes:
  sisgea-message-broker-data: