x-podman:
  in_pod: false
  pod_args: --replace

services:
  timetable-generator:
    user: root
    build:
      context: .
      dockerfile: Dockerfile
      target: devcontainer
    command: bash -c 'sleep infinity;'
    working_dir: /app/
    userns_mode: keep-id:uid=1000,gid=1000
    env_file:
      - .env

  message-broker:
    image: docker.io/rabbitmq:3.13-management-alpine
    container_name: rabbitmq
    env_file:
      - .env
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

volumes:
  rabbitmq-data:
