<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>Ladesa.TimetableGenerator.Application</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Ladesa.TimetableGenerator.Domain\Ladesa.TimetableGenerator.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Ladesa.Messages.TimetableGenerator.V1" Version="0.0.2" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.0" />
  </ItemGroup>
</Project>
