<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>library</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>Ladesa.TimetableGenerator.Infrastructure.Solver</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Ladesa.TimetableGenerator.Domain\Ladesa.TimetableGenerator.Domain.csproj" />
    <ProjectReference Include="..\Ladesa.TimetableGenerator.Application\Ladesa.TimetableGenerator.Application.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Google.OrTools" Version="9.14.6206" />
    <PackageReference Include="Ical.Net" Version="5.1.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.0" />
  </ItemGroup>
</Project>
