// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: core/application/dtos/generate_request.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Ladesa.TimetableGenerator.v1.Service.Infrastructure.Protos {

  /// <summary>Holder for reflection information generated from core/application/dtos/generate_request.proto</summary>
  public static partial class GenerateRequestReflection {

    #region Descriptor
    /// <summary>File descriptor for core/application/dtos/generate_request.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GenerateRequestReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cixjb3JlL2FwcGxpY2F0aW9uL2R0b3MvZ2VuZXJhdGVfcmVxdWVzdC5wcm90",
            "bxIibGFkZXNhLnRpbWV0YWJsZV9nZW5lcmF0b3IudjEuZHRvcxogY29yZS9k",
            "b21haW4vZW50aXRpZXMvZGlhcnkucHJvdG8aImNvcmUvZG9tYWluL2VudGl0",
            "aWVzL3RlYWNoZXIucHJvdG8aIGNvcmUvZG9tYWluL2VudGl0aWVzL2dyb3Vw",
            "LnByb3RvGiljb3JlL2RvbWFpbi9lbnRpdGllcy90aW1ldGFibGVfZ3JpZC5w",
            "cm90bxopY29yZS9kb21haW4vdmFsdWVfb2JqZWN0cy90aW1lX3Nsb3QucHJv",
            "dG8itQMKEkdlbmVyYXRlUmVxdWVzdER0bxISCgpkYXRlX3N0YXJ0GAEgASgJ",
            "EhAKCGRhdGVfZW5kGAIgASgJEj0KBmdyb3VwcxgDIAMoCzItLmxhZGVzYS50",
            "aW1ldGFibGVfZ2VuZXJhdG9yLnYxLmVudGl0aWVzLkdyb3VwEkEKCHRlYWNo",
            "ZXJzGAQgAygLMi8ubGFkZXNhLnRpbWV0YWJsZV9nZW5lcmF0b3IudjEuZW50",
            "aXRpZXMuVGVhY2hlchI9CgZkaWFyeXMYBSADKAsyLS5sYWRlc2EudGltZXRh",
            "YmxlX2dlbmVyYXRvci52MS5lbnRpdGllcy5EaWFyeRI/Cgp0aW1lX3Nsb3Rz",
            "GAYgAygLMisubGFkZXNhLnRpbWV0YWJsZV9nZW5lcmF0b3IudjEudm9zLlRp",
            "bWVTbG90ElsKF3ByZXZpb3VzX3RpbWV0YWJsZV9ncmlkGAcgASgLMjUubGFk",
            "ZXNhLnRpbWV0YWJsZV9nZW5lcmF0b3IudjEuZW50aXRpZXMuVGltZXRhYmxl",
            "R3JpZEgAiAEBQhoKGF9wcmV2aW91c190aW1ldGFibGVfZ3JpZEImqgIjTGFk",
            "ZXNhLlRpbWV0YWJsZUdlbmVyYXRvci52MS5Qcm90b3NiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Ladesa.TimetableGenerator.v1.Service.Infrastructure.Protos.DiaryReflection.Descriptor, global::Ladesa.TimetableGenerator.v1.Service.Infrastructure.Protos.TeacherReflection.Descriptor, global::Ladesa.TimetableGenerator.v1.Service.Infrastructure.Protos.GroupReflection.Descriptor, global::Ladesa.TimetableGenerator.v1.Service.Infrastructure.Protos.TimetableGridReflection.Descriptor, global::Ladesa.TimetableGenerator.v1.Service.Infrastructure.Protos.TimeSlotReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Ladesa.TimetableGenerator.v1.Service.Infrastructure.Protos.GenerateRequestDto), global::Ladesa.TimetableGenerator.v1.Service.Infrastructure.Protos.GenerateRequestDto.Parser, new[]{ "DateStart", "DateEnd", "Groups", "Teachers", "Diarys", "TimeSlots", "PreviousTimetableGrid" }, new[]{ "PreviousTimetableGrid" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class GenerateRequestDto : pb::IMessage<GenerateRequestDto>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GenerateRequestDto> _parser = new pb::MessageParser<GenerateRequestDto>(() => new GenerateRequestDto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GenerateRequestDto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Ladesa.TimetableGenerator.v1.Service.Infrastructure.Protos.GenerateRequestReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GenerateRequestDto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GenerateRequestDto(GenerateRequestDto other) : this() {
      dateStart_ = other.dateStart_;
      dateEnd_ = other.dateEnd_;
      groups_ = other.groups_.Clone();
      teachers_ = other.teachers_.Clone();
      diarys_ = other.diarys_.Clone();
      timeSlots_ = other.timeSlots_.Clone();
      previousTimetableGrid_ = other.previousTimetableGrid_ != null ? other.previousTimetableGrid_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GenerateRequestDto Clone() {
      return new GenerateRequestDto(this);
    }

    /// <summary>Field number for the "date_start" field.</summary>
    public const int DateStartFieldNumber = 1;
    private string dateStart_ = "";
    /// <summary>
    /// date-time
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string DateStart {
      get { return dateStart_; }
      set {
        dateStart_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "date_end" field.</summary>
    public const int DateEndFieldNumber = 2;
    private string dateEnd_ = "";
    /// <summary>
    /// date-time
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string DateEnd {
      get { return dateEnd_; }
      set {
        dateEnd_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "groups" field.</summary>
    public const int GroupsFieldNumber = 3;
    private static readonly pb::FieldCodec<global::Ladesa.TimetableGenerator.v1.Service.Infrastructure.Protos.Group> _repeated_groups_codec
        = pb::FieldCodec.ForMessage(26, global::Ladesa.TimetableGenerator.v1.Service.Infrastructure.Protos.Group.Parser);
    private readonly pbc::RepeatedField<global::Ladesa.TimetableGenerator.v1.Service.Infrastructure.Protos.Group> groups_ = new pbc::RepeatedField<global::Ladesa.TimetableGenerator.v1.Service.Infrastructure.Protos.Group>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Ladesa.TimetableGenerator.v1.Service.Infrastructure.Protos.Group> Groups {
      get { return groups_; }
    }

    /// <summary>Field number for the "teachers" field.</summary>
    public const int TeachersFieldNumber = 4;
    private static readonly pb::FieldCodec<global::Ladesa.TimetableGenerator.v1.Service.Infrastructure.Protos.Teacher> _repeated_teachers_codec
        = pb::FieldCodec.ForMessage(34, global::Ladesa.TimetableGenerator.v1.Service.Infrastructure.Protos.Teacher.Parser);
    private readonly pbc::RepeatedField<global::Ladesa.TimetableGenerator.v1.Service.Infrastructure.Protos.Teacher> teachers_ = new pbc::RepeatedField<global::Ladesa.TimetableGenerator.v1.Service.Infrastructure.Protos.Teacher>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Ladesa.TimetableGenerator.v1.Service.Infrastructure.Protos.Teacher> Teachers {
      get { return teachers_; }
    }

    /// <summary>Field number for the "diarys" field.</summary>
    public const int DiarysFieldNumber = 5;
    private static readonly pb::FieldCodec<global::Ladesa.TimetableGenerator.v1.Service.Infrastructure.Protos.Diary> _repeated_diarys_codec
        = pb::FieldCodec.ForMessage(42, global::Ladesa.TimetableGenerator.v1.Service.Infrastructure.Protos.Diary.Parser);
    private readonly pbc::RepeatedField<global::Ladesa.TimetableGenerator.v1.Service.Infrastructure.Protos.Diary> diarys_ = new pbc::RepeatedField<global::Ladesa.TimetableGenerator.v1.Service.Infrastructure.Protos.Diary>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Ladesa.TimetableGenerator.v1.Service.Infrastructure.Protos.Diary> Diarys {
      get { return diarys_; }
    }

    /// <summary>Field number for the "time_slots" field.</summary>
    public const int TimeSlotsFieldNumber = 6;
    private static readonly pb::FieldCodec<global::Ladesa.TimetableGenerator.v1.Service.Infrastructure.Protos.TimeSlot> _repeated_timeSlots_codec
        = pb::FieldCodec.ForMessage(50, global::Ladesa.TimetableGenerator.v1.Service.Infrastructure.Protos.TimeSlot.Parser);
    private readonly pbc::RepeatedField<global::Ladesa.TimetableGenerator.v1.Service.Infrastructure.Protos.TimeSlot> timeSlots_ = new pbc::RepeatedField<global::Ladesa.TimetableGenerator.v1.Service.Infrastructure.Protos.TimeSlot>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Ladesa.TimetableGenerator.v1.Service.Infrastructure.Protos.TimeSlot> TimeSlots {
      get { return timeSlots_; }
    }

    /// <summary>Field number for the "previous_timetable_grid" field.</summary>
    public const int PreviousTimetableGridFieldNumber = 7;
    private global::Ladesa.TimetableGenerator.v1.Service.Infrastructure.Protos.TimetableGrid previousTimetableGrid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Ladesa.TimetableGenerator.v1.Service.Infrastructure.Protos.TimetableGrid PreviousTimetableGrid {
      get { return previousTimetableGrid_; }
      set {
        previousTimetableGrid_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GenerateRequestDto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GenerateRequestDto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (DateStart != other.DateStart) return false;
      if (DateEnd != other.DateEnd) return false;
      if(!groups_.Equals(other.groups_)) return false;
      if(!teachers_.Equals(other.teachers_)) return false;
      if(!diarys_.Equals(other.diarys_)) return false;
      if(!timeSlots_.Equals(other.timeSlots_)) return false;
      if (!object.Equals(PreviousTimetableGrid, other.PreviousTimetableGrid)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (DateStart.Length != 0) hash ^= DateStart.GetHashCode();
      if (DateEnd.Length != 0) hash ^= DateEnd.GetHashCode();
      hash ^= groups_.GetHashCode();
      hash ^= teachers_.GetHashCode();
      hash ^= diarys_.GetHashCode();
      hash ^= timeSlots_.GetHashCode();
      if (previousTimetableGrid_ != null) hash ^= PreviousTimetableGrid.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (DateStart.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(DateStart);
      }
      if (DateEnd.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(DateEnd);
      }
      groups_.WriteTo(output, _repeated_groups_codec);
      teachers_.WriteTo(output, _repeated_teachers_codec);
      diarys_.WriteTo(output, _repeated_diarys_codec);
      timeSlots_.WriteTo(output, _repeated_timeSlots_codec);
      if (previousTimetableGrid_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(PreviousTimetableGrid);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (DateStart.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(DateStart);
      }
      if (DateEnd.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(DateEnd);
      }
      groups_.WriteTo(ref output, _repeated_groups_codec);
      teachers_.WriteTo(ref output, _repeated_teachers_codec);
      diarys_.WriteTo(ref output, _repeated_diarys_codec);
      timeSlots_.WriteTo(ref output, _repeated_timeSlots_codec);
      if (previousTimetableGrid_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(PreviousTimetableGrid);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (DateStart.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DateStart);
      }
      if (DateEnd.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DateEnd);
      }
      size += groups_.CalculateSize(_repeated_groups_codec);
      size += teachers_.CalculateSize(_repeated_teachers_codec);
      size += diarys_.CalculateSize(_repeated_diarys_codec);
      size += timeSlots_.CalculateSize(_repeated_timeSlots_codec);
      if (previousTimetableGrid_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PreviousTimetableGrid);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GenerateRequestDto other) {
      if (other == null) {
        return;
      }
      if (other.DateStart.Length != 0) {
        DateStart = other.DateStart;
      }
      if (other.DateEnd.Length != 0) {
        DateEnd = other.DateEnd;
      }
      groups_.Add(other.groups_);
      teachers_.Add(other.teachers_);
      diarys_.Add(other.diarys_);
      timeSlots_.Add(other.timeSlots_);
      if (other.previousTimetableGrid_ != null) {
        if (previousTimetableGrid_ == null) {
          PreviousTimetableGrid = new global::Ladesa.TimetableGenerator.v1.Service.Infrastructure.Protos.TimetableGrid();
        }
        PreviousTimetableGrid.MergeFrom(other.PreviousTimetableGrid);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            DateStart = input.ReadString();
            break;
          }
          case 18: {
            DateEnd = input.ReadString();
            break;
          }
          case 26: {
            groups_.AddEntriesFrom(input, _repeated_groups_codec);
            break;
          }
          case 34: {
            teachers_.AddEntriesFrom(input, _repeated_teachers_codec);
            break;
          }
          case 42: {
            diarys_.AddEntriesFrom(input, _repeated_diarys_codec);
            break;
          }
          case 50: {
            timeSlots_.AddEntriesFrom(input, _repeated_timeSlots_codec);
            break;
          }
          case 58: {
            if (previousTimetableGrid_ == null) {
              PreviousTimetableGrid = new global::Ladesa.TimetableGenerator.v1.Service.Infrastructure.Protos.TimetableGrid();
            }
            input.ReadMessage(PreviousTimetableGrid);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            DateStart = input.ReadString();
            break;
          }
          case 18: {
            DateEnd = input.ReadString();
            break;
          }
          case 26: {
            groups_.AddEntriesFrom(ref input, _repeated_groups_codec);
            break;
          }
          case 34: {
            teachers_.AddEntriesFrom(ref input, _repeated_teachers_codec);
            break;
          }
          case 42: {
            diarys_.AddEntriesFrom(ref input, _repeated_diarys_codec);
            break;
          }
          case 50: {
            timeSlots_.AddEntriesFrom(ref input, _repeated_timeSlots_codec);
            break;
          }
          case 58: {
            if (previousTimetableGrid_ == null) {
              PreviousTimetableGrid = new global::Ladesa.TimetableGenerator.v1.Service.Infrastructure.Protos.TimetableGrid();
            }
            input.ReadMessage(PreviousTimetableGrid);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
