// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: core/domain/entities/timetable_grid.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Ladesa.TimetableGenerator.v1.Service.Infrastructure.Protos {

  /// <summary>Holder for reflection information generated from core/domain/entities/timetable_grid.proto</summary>
  public static partial class TimetableGridReflection {

    #region Descriptor
    /// <summary>File descriptor for core/domain/entities/timetable_grid.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TimetableGridReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ciljb3JlL2RvbWFpbi9lbnRpdGllcy90aW1ldGFibGVfZ3JpZC5wcm90bxIm",
            "bGFkZXNhLnRpbWV0YWJsZV9nZW5lcmF0b3IudjEuZW50aXRpZXMaKWNvcmUv",
            "ZG9tYWluL3ZhbHVlX29iamVjdHMvdGltZV9zbG90LnByb3RvGjJjb3JlL2Rv",
            "bWFpbi9lbnRpdGllcy90aW1ldGFibGVfZ3JpZF9zY2hlZHVsZS5wcm90byLI",
            "AQoNVGltZXRhYmxlR3JpZBISCgpkYXRlX3N0YXJ0GAEgASgJEhAKCGRhdGVf",
            "ZW5kGAIgASgJEj8KCnRpbWVfc2xvdHMYAyADKAsyKy5sYWRlc2EudGltZXRh",
            "YmxlX2dlbmVyYXRvci52MS52b3MuVGltZVNsb3QSUAoJc2NoZWR1bGVzGAQg",
            "AygLMj0ubGFkZXNhLnRpbWV0YWJsZV9nZW5lcmF0b3IudjEuZW50aXRpZXMu",
            "VGltZXRhYmxlR3JpZFNjaGVkdWxlQiaqAiNMYWRlc2EuVGltZXRhYmxlR2Vu",
            "ZXJhdG9yLnYxLlByb3Rvc2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Ladesa.TimetableGenerator.v1.Service.Infrastructure.Protos.TimeSlotReflection.Descriptor, global::Ladesa.TimetableGenerator.v1.Service.Infrastructure.Protos.TimetableGridScheduleReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Ladesa.TimetableGenerator.v1.Service.Infrastructure.Protos.TimetableGrid), global::Ladesa.TimetableGenerator.v1.Service.Infrastructure.Protos.TimetableGrid.Parser, new[]{ "DateStart", "DateEnd", "TimeSlots", "Schedules" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class TimetableGrid : pb::IMessage<TimetableGrid>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TimetableGrid> _parser = new pb::MessageParser<TimetableGrid>(() => new TimetableGrid());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TimetableGrid> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Ladesa.TimetableGenerator.v1.Service.Infrastructure.Protos.TimetableGridReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TimetableGrid() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TimetableGrid(TimetableGrid other) : this() {
      dateStart_ = other.dateStart_;
      dateEnd_ = other.dateEnd_;
      timeSlots_ = other.timeSlots_.Clone();
      schedules_ = other.schedules_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TimetableGrid Clone() {
      return new TimetableGrid(this);
    }

    /// <summary>Field number for the "date_start" field.</summary>
    public const int DateStartFieldNumber = 1;
    private string dateStart_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string DateStart {
      get { return dateStart_; }
      set {
        dateStart_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "date_end" field.</summary>
    public const int DateEndFieldNumber = 2;
    private string dateEnd_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string DateEnd {
      get { return dateEnd_; }
      set {
        dateEnd_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "time_slots" field.</summary>
    public const int TimeSlotsFieldNumber = 3;
    private static readonly pb::FieldCodec<global::Ladesa.TimetableGenerator.v1.Service.Infrastructure.Protos.TimeSlot> _repeated_timeSlots_codec
        = pb::FieldCodec.ForMessage(26, global::Ladesa.TimetableGenerator.v1.Service.Infrastructure.Protos.TimeSlot.Parser);
    private readonly pbc::RepeatedField<global::Ladesa.TimetableGenerator.v1.Service.Infrastructure.Protos.TimeSlot> timeSlots_ = new pbc::RepeatedField<global::Ladesa.TimetableGenerator.v1.Service.Infrastructure.Protos.TimeSlot>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Ladesa.TimetableGenerator.v1.Service.Infrastructure.Protos.TimeSlot> TimeSlots {
      get { return timeSlots_; }
    }

    /// <summary>Field number for the "schedules" field.</summary>
    public const int SchedulesFieldNumber = 4;
    private static readonly pb::FieldCodec<global::Ladesa.TimetableGenerator.v1.Service.Infrastructure.Protos.TimetableGridSchedule> _repeated_schedules_codec
        = pb::FieldCodec.ForMessage(34, global::Ladesa.TimetableGenerator.v1.Service.Infrastructure.Protos.TimetableGridSchedule.Parser);
    private readonly pbc::RepeatedField<global::Ladesa.TimetableGenerator.v1.Service.Infrastructure.Protos.TimetableGridSchedule> schedules_ = new pbc::RepeatedField<global::Ladesa.TimetableGenerator.v1.Service.Infrastructure.Protos.TimetableGridSchedule>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Ladesa.TimetableGenerator.v1.Service.Infrastructure.Protos.TimetableGridSchedule> Schedules {
      get { return schedules_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TimetableGrid);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TimetableGrid other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (DateStart != other.DateStart) return false;
      if (DateEnd != other.DateEnd) return false;
      if(!timeSlots_.Equals(other.timeSlots_)) return false;
      if(!schedules_.Equals(other.schedules_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (DateStart.Length != 0) hash ^= DateStart.GetHashCode();
      if (DateEnd.Length != 0) hash ^= DateEnd.GetHashCode();
      hash ^= timeSlots_.GetHashCode();
      hash ^= schedules_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (DateStart.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(DateStart);
      }
      if (DateEnd.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(DateEnd);
      }
      timeSlots_.WriteTo(output, _repeated_timeSlots_codec);
      schedules_.WriteTo(output, _repeated_schedules_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (DateStart.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(DateStart);
      }
      if (DateEnd.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(DateEnd);
      }
      timeSlots_.WriteTo(ref output, _repeated_timeSlots_codec);
      schedules_.WriteTo(ref output, _repeated_schedules_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (DateStart.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DateStart);
      }
      if (DateEnd.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DateEnd);
      }
      size += timeSlots_.CalculateSize(_repeated_timeSlots_codec);
      size += schedules_.CalculateSize(_repeated_schedules_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TimetableGrid other) {
      if (other == null) {
        return;
      }
      if (other.DateStart.Length != 0) {
        DateStart = other.DateStart;
      }
      if (other.DateEnd.Length != 0) {
        DateEnd = other.DateEnd;
      }
      timeSlots_.Add(other.timeSlots_);
      schedules_.Add(other.schedules_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            DateStart = input.ReadString();
            break;
          }
          case 18: {
            DateEnd = input.ReadString();
            break;
          }
          case 26: {
            timeSlots_.AddEntriesFrom(input, _repeated_timeSlots_codec);
            break;
          }
          case 34: {
            schedules_.AddEntriesFrom(input, _repeated_schedules_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            DateStart = input.ReadString();
            break;
          }
          case 18: {
            DateEnd = input.ReadString();
            break;
          }
          case 26: {
            timeSlots_.AddEntriesFrom(ref input, _repeated_timeSlots_codec);
            break;
          }
          case 34: {
            schedules_.AddEntriesFrom(ref input, _repeated_schedules_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
