// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: core/domain/value_objects/week_day.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Ladesa.TimetableGenerator.v1.Service.Infrastructure.Protos {

  /// <summary>Holder for reflection information generated from core/domain/value_objects/week_day.proto</summary>
  public static partial class WeekDayReflection {

    #region Descriptor
    /// <summary>File descriptor for core/domain/value_objects/week_day.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static WeekDayReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cihjb3JlL2RvbWFpbi92YWx1ZV9vYmplY3RzL3dlZWtfZGF5LnByb3RvEiFs",
            "YWRlc2EudGltZXRhYmxlX2dlbmVyYXRvci52MS52b3MqZQoHV2Vla0RheRIK",
            "CgZTdW5kYXkQABIKCgZNb25kYXkQARILCgdUdWVzZGF5EAISDQoJV2VkbmVz",
            "ZGF5EAMSDAoIVGh1cnNkYXkQBBIKCgZGcmlkYXkQBRIMCghTYXR1cmRheRAG",
            "QiaqAiNMYWRlc2EuVGltZXRhYmxlR2VuZXJhdG9yLnYxLlByb3Rvc2IGcHJv",
            "dG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Ladesa.TimetableGenerator.v1.Service.Infrastructure.Protos.WeekDay), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum WeekDay {
    [pbr::OriginalName("Sunday")] Sunday = 0,
    [pbr::OriginalName("Monday")] Monday = 1,
    [pbr::OriginalName("Tuesday")] Tuesday = 2,
    [pbr::OriginalName("Wednesday")] Wednesday = 3,
    [pbr::OriginalName("Thursday")] Thursday = 4,
    [pbr::OriginalName("Friday")] Friday = 5,
    [pbr::OriginalName("Saturday")] Saturday = 6,
  }

  #endregion

}

#endregion Designer generated code
