apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisicalsecret-timetable-generator-configs-dev
  namespace: ladesa-ro-development
  labels:
    app.kubernetes.io/name: api-configs
    env: dev

spec:
  hostAPI: https://infisical.ladesa.com.br/api

  authentication:
    universalAuth:
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: default
      secretsScope:
        envSlug: dev
        projectSlug: timetable-generator-xh2x
        recursive: true
        secretsPath: /

  managedSecretReference:
    secretName: ladesa-ro-timetable-generator-config
    secretNamespace: ladesa-ro-development
    secretType: Opaque
    creationPolicy: Owner

  resyncInterval: 60