// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: messages/generator-payload.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Ladesa.TimetableGenerator.Service.Infrastructure.Protos {

  /// <summary>Holder for reflection information generated from messages/generator-payload.proto</summary>
  public static partial class GeneratorPayloadReflection {

    #region Descriptor
    /// <summary>File descriptor for messages/generator-payload.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GeneratorPayloadReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiBtZXNzYWdlcy9nZW5lcmF0b3ItcGF5bG9hZC5wcm90bxIcTGFkZXNhLlRp",
            "bWV0YWJsZUdlbmVyYXRvci52MRoYZW50aXRpZXMvZGlhcnktZHRvLnByb3Rv",
            "GhplbnRpdGllcy90ZWFjaGVyLWR0by5wcm90bxoYZW50aXRpZXMvZ3JvdXAt",
            "ZHRvLnByb3RvGiF2YWx1ZS1vYmplY3RzL3RpbWUtc2xvdC1kdG8ucHJvdG8i",
            "ugIKE0dlbmVyYXRvclBheWxvYWREdG8SEgoKcmVxdWVzdF9pZBgBIAEoCRIS",
            "CgpkYXRlX3N0YXJ0GAIgASgJEhAKCGRhdGVfZW5kGAMgASgJEjYKBmRpYXJ5",
            "cxgEIAMoCzImLkxhZGVzYS5UaW1ldGFibGVHZW5lcmF0b3IudjEuRGlhcnlE",
            "dG8SOgoIdGVhY2hlcnMYBSADKAsyKC5MYWRlc2EuVGltZXRhYmxlR2VuZXJh",
            "dG9yLnYxLlRlYWNoZXJEdG8SNgoGZ3JvdXBzGAYgAygLMiYuTGFkZXNhLlRp",
            "bWV0YWJsZUdlbmVyYXRvci52MS5Hcm91cER0bxI9Cgp0aW1lX3Nsb3RzGAcg",
            "AygLMikuTGFkZXNhLlRpbWV0YWJsZUdlbmVyYXRvci52MS5UaW1lU2xvdER0",
            "b2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.DiaryDtoReflection.Descriptor, global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.TeacherDtoReflection.Descriptor, global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.GroupDtoReflection.Descriptor, global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.TimeSlotDtoReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.GeneratorPayloadDto), global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.GeneratorPayloadDto.Parser, new[]{ "RequestId", "DateStart", "DateEnd", "Diarys", "Teachers", "Groups", "TimeSlots" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class GeneratorPayloadDto : pb::IMessage<GeneratorPayloadDto>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GeneratorPayloadDto> _parser = new pb::MessageParser<GeneratorPayloadDto>(() => new GeneratorPayloadDto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GeneratorPayloadDto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.GeneratorPayloadReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GeneratorPayloadDto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GeneratorPayloadDto(GeneratorPayloadDto other) : this() {
      requestId_ = other.requestId_;
      dateStart_ = other.dateStart_;
      dateEnd_ = other.dateEnd_;
      diarys_ = other.diarys_.Clone();
      teachers_ = other.teachers_.Clone();
      groups_ = other.groups_.Clone();
      timeSlots_ = other.timeSlots_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GeneratorPayloadDto Clone() {
      return new GeneratorPayloadDto(this);
    }

    /// <summary>Field number for the "request_id" field.</summary>
    public const int RequestIdFieldNumber = 1;
    private string requestId_ = "";
    /// <summary>
    /// guid
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string RequestId {
      get { return requestId_; }
      set {
        requestId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "date_start" field.</summary>
    public const int DateStartFieldNumber = 2;
    private string dateStart_ = "";
    /// <summary>
    /// date-time
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string DateStart {
      get { return dateStart_; }
      set {
        dateStart_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "date_end" field.</summary>
    public const int DateEndFieldNumber = 3;
    private string dateEnd_ = "";
    /// <summary>
    /// date-time
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string DateEnd {
      get { return dateEnd_; }
      set {
        dateEnd_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "diarys" field.</summary>
    public const int DiarysFieldNumber = 4;
    private static readonly pb::FieldCodec<global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.DiaryDto> _repeated_diarys_codec
        = pb::FieldCodec.ForMessage(34, global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.DiaryDto.Parser);
    private readonly pbc::RepeatedField<global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.DiaryDto> diarys_ = new pbc::RepeatedField<global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.DiaryDto>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.DiaryDto> Diarys {
      get { return diarys_; }
    }

    /// <summary>Field number for the "teachers" field.</summary>
    public const int TeachersFieldNumber = 5;
    private static readonly pb::FieldCodec<global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.TeacherDto> _repeated_teachers_codec
        = pb::FieldCodec.ForMessage(42, global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.TeacherDto.Parser);
    private readonly pbc::RepeatedField<global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.TeacherDto> teachers_ = new pbc::RepeatedField<global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.TeacherDto>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.TeacherDto> Teachers {
      get { return teachers_; }
    }

    /// <summary>Field number for the "groups" field.</summary>
    public const int GroupsFieldNumber = 6;
    private static readonly pb::FieldCodec<global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.GroupDto> _repeated_groups_codec
        = pb::FieldCodec.ForMessage(50, global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.GroupDto.Parser);
    private readonly pbc::RepeatedField<global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.GroupDto> groups_ = new pbc::RepeatedField<global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.GroupDto>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.GroupDto> Groups {
      get { return groups_; }
    }

    /// <summary>Field number for the "time_slots" field.</summary>
    public const int TimeSlotsFieldNumber = 7;
    private static readonly pb::FieldCodec<global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.TimeSlotDto> _repeated_timeSlots_codec
        = pb::FieldCodec.ForMessage(58, global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.TimeSlotDto.Parser);
    private readonly pbc::RepeatedField<global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.TimeSlotDto> timeSlots_ = new pbc::RepeatedField<global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.TimeSlotDto>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Ladesa.TimetableGenerator.Service.Infrastructure.Protos.TimeSlotDto> TimeSlots {
      get { return timeSlots_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GeneratorPayloadDto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GeneratorPayloadDto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (RequestId != other.RequestId) return false;
      if (DateStart != other.DateStart) return false;
      if (DateEnd != other.DateEnd) return false;
      if(!diarys_.Equals(other.diarys_)) return false;
      if(!teachers_.Equals(other.teachers_)) return false;
      if(!groups_.Equals(other.groups_)) return false;
      if(!timeSlots_.Equals(other.timeSlots_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (RequestId.Length != 0) hash ^= RequestId.GetHashCode();
      if (DateStart.Length != 0) hash ^= DateStart.GetHashCode();
      if (DateEnd.Length != 0) hash ^= DateEnd.GetHashCode();
      hash ^= diarys_.GetHashCode();
      hash ^= teachers_.GetHashCode();
      hash ^= groups_.GetHashCode();
      hash ^= timeSlots_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (RequestId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(RequestId);
      }
      if (DateStart.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(DateStart);
      }
      if (DateEnd.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(DateEnd);
      }
      diarys_.WriteTo(output, _repeated_diarys_codec);
      teachers_.WriteTo(output, _repeated_teachers_codec);
      groups_.WriteTo(output, _repeated_groups_codec);
      timeSlots_.WriteTo(output, _repeated_timeSlots_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (RequestId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(RequestId);
      }
      if (DateStart.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(DateStart);
      }
      if (DateEnd.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(DateEnd);
      }
      diarys_.WriteTo(ref output, _repeated_diarys_codec);
      teachers_.WriteTo(ref output, _repeated_teachers_codec);
      groups_.WriteTo(ref output, _repeated_groups_codec);
      timeSlots_.WriteTo(ref output, _repeated_timeSlots_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (RequestId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(RequestId);
      }
      if (DateStart.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DateStart);
      }
      if (DateEnd.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DateEnd);
      }
      size += diarys_.CalculateSize(_repeated_diarys_codec);
      size += teachers_.CalculateSize(_repeated_teachers_codec);
      size += groups_.CalculateSize(_repeated_groups_codec);
      size += timeSlots_.CalculateSize(_repeated_timeSlots_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GeneratorPayloadDto other) {
      if (other == null) {
        return;
      }
      if (other.RequestId.Length != 0) {
        RequestId = other.RequestId;
      }
      if (other.DateStart.Length != 0) {
        DateStart = other.DateStart;
      }
      if (other.DateEnd.Length != 0) {
        DateEnd = other.DateEnd;
      }
      diarys_.Add(other.diarys_);
      teachers_.Add(other.teachers_);
      groups_.Add(other.groups_);
      timeSlots_.Add(other.timeSlots_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            RequestId = input.ReadString();
            break;
          }
          case 18: {
            DateStart = input.ReadString();
            break;
          }
          case 26: {
            DateEnd = input.ReadString();
            break;
          }
          case 34: {
            diarys_.AddEntriesFrom(input, _repeated_diarys_codec);
            break;
          }
          case 42: {
            teachers_.AddEntriesFrom(input, _repeated_teachers_codec);
            break;
          }
          case 50: {
            groups_.AddEntriesFrom(input, _repeated_groups_codec);
            break;
          }
          case 58: {
            timeSlots_.AddEntriesFrom(input, _repeated_timeSlots_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            RequestId = input.ReadString();
            break;
          }
          case 18: {
            DateStart = input.ReadString();
            break;
          }
          case 26: {
            DateEnd = input.ReadString();
            break;
          }
          case 34: {
            diarys_.AddEntriesFrom(ref input, _repeated_diarys_codec);
            break;
          }
          case 42: {
            teachers_.AddEntriesFrom(ref input, _repeated_teachers_codec);
            break;
          }
          case 50: {
            groups_.AddEntriesFrom(ref input, _repeated_groups_codec);
            break;
          }
          case 58: {
            timeSlots_.AddEntriesFrom(ref input, _repeated_timeSlots_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
