// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: value-objects/week-day-dto.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Ladesa.TimetableGenerator.Service.Infrastructure.Protos {

  /// <summary>Holder for reflection information generated from value-objects/week-day-dto.proto</summary>
  public static partial class WeekDayDtoReflection {

    #region Descriptor
    /// <summary>File descriptor for value-objects/week-day-dto.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static WeekDayDtoReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiB2YWx1ZS1vYmplY3RzL3dlZWstZGF5LWR0by5wcm90bxIcTGFkZXNhLlRp",
            "bWV0YWJsZUdlbmVyYXRvci52MSpoCgpXZWVrRGF5RHRvEgoKBlN1bmRheRAA",
            "EgoKBk1vbmRheRABEgsKB1R1ZXNkYXkQAhINCglXZWRuZXNkYXkQAxIMCghU",
            "aHVyc2RheRAEEgoKBkZyaWRheRAFEgwKCFNhdHVyZGF5EAZiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Ladesa.TimetableGenerator.V1.WeekDayDto), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum WeekDayDto {
    [pbr::OriginalName("Sunday")] Sunday = 0,
    [pbr::OriginalName("Monday")] Monday = 1,
    [pbr::OriginalName("Tuesday")] Tuesday = 2,
    [pbr::OriginalName("Wednesday")] Wednesday = 3,
    [pbr::OriginalName("Thursday")] Thursday = 4,
    [pbr::OriginalName("Friday")] Friday = 5,
    [pbr::OriginalName("Saturday")] Saturday = 6,
  }

  #endregion

}

#endregion Designer generated code
