apiVersion: v1
kind: Service
metadata:
  name: ladesa-ro-timetable-generator
  labels:
    app: ladesa-ro-timetable-generator
  namespace: ladesa-ro-development
spec:
  type: NodePort
  selector:
    app: ladesa-ro-timetable-generator
  ports:
    - name: timetable-generator-service
      port: 80
      targetPort: timetable-generator-port