<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>library</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <RootNamespace>Ladesa.TimetableGenerator.Core</RootNamespace>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Google.OrTools" Version="9.14.6206"/>
    </ItemGroup>
    <ItemGroup>
    <Compile Remove="Timetable\Domain\ValueObjects\SlotDeTempo.cs" />
    <Compile Remove="Timetable\Presentation\DTOs\Entities\GeradorPayloadDto.cs" />
    <Compile Remove="Timetable\Presentation\DTOs\Entities\HorarioGeradoDto.cs" />
    <Compile Remove="Timetable\Presentation\DTOs\ValueObjects\RegraDisponibilidadeDto.cs" />
    <Compile Remove="Timetable\Presentation\Mappers\Entities\HorarioGeradoAulaMapper.cs" />
    <Compile Remove="Timetable\Presentation\Mappers\ValueObjects\RegraDisponibilidadeMapper.cs" />
  </ItemGroup>
</Project>
