<Project Sdk="Microsoft.NET.Sdk.Worker">
    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>dcdb8d1c-71e7-4c9c-950d-9711dd395943</UserSecretsId>
        <RootNamespace>Ladesa.TimetableGenerator.Service</RootNamespace>
    </PropertyGroup>
    <ItemGroup Label="Dependencies">
        <PackageReference Include="Google.Protobuf" Version="3.33.0" />
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.8" />
        <PackageReference Include="RabbitMQ.Client" Version="7.1.2" />
        <PackageReference Include="NJsonSchema" Version="11.0.0" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.6" />
    </ItemGroup>
    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\Core\Core.csproj" />
    </ItemGroup>
</Project>
