<Project Sdk="Microsoft.NET.Sdk.Worker">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dcdb8d1c-71e7-4c9c-950d-9711dd395943</UserSecretsId>
  </PropertyGroup>
  <ItemGroup Label="Dependencies">
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.6" />
    <PackageReference Include="RabbitMQ.Client" Version="7.1.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\gerar-horario-core\gerar-horario-core.csproj" />
  </ItemGroup>
</Project>
