name: CD - Build, publish and deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: cd-${{ github.ref }}

env:
  REGISTRY: ghcr.io
  REGISTRY_USERNAME: ${{ github.actor }}
  REGISTRY_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  IMAGE_BASENAME: ${{ github.repository }}

jobs:
  timetable-api-ci-image:
    name: "CI: Build and Publish API Image"
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    environment:
      name: ci-cd-timetable-generator-dev

    steps:
      - name: Checkout source code
        uses: actions/checkout@v6

      - name: Set up QEMU
        uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd

      - name: Login to GitHub Container Registry
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.REGISTRY_USERNAME }}
          password: ${{ env.REGISTRY_TOKEN }}

      - name: Build and push API image
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f
        with:
          context: .
          target: timetable-api-runtime
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_BASENAME }}/timetable-api:development
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_BASENAME }}/timetable-api:cache-development
          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_BASENAME }}/timetable-api:cache-development,mode=max

  timetable-worker-ci-image:
    name: "CI: Build and Publish Worker Image"
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    environment:
      name: ci-cd-timetable-generator-dev

    steps:
      - name: Checkout source code
        uses: actions/checkout@v6

      - name: Set up QEMU
        uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd

      - name: Login to GitHub Container Registry
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.REGISTRY_USERNAME }}
          password: ${{ env.REGISTRY_TOKEN }}

      - name: Build and push Worker image
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f
        with:
          context: .
          target: timetable-worker-runtime
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_BASENAME }}/timetable-worker:development
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_BASENAME }}/timetable-worker:cache-development
          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_BASENAME }}/timetable-worker:cache-development,mode=max

  timetable-generator-cd-cluster:
    name: "CD: Deploy to Kubernetes Cluster"

    runs-on: dev-deploy

    permissions:
      contents: read

    needs: [ timetable-api-ci-image, timetable-worker-ci-image ]

    environment:
      name: ci-cd-timetable-generator-dev

    steps:
      - name: Checkout source code
        uses: actions/checkout@v6

      - name: Deploy to Kubernetes
        shell: bash
        working-directory: ./.deploy/development/
        run: bash ./deploy.sh
